name: "Workflow to setup aPG"

on:
  push:
    branches:
    - main
    - release/*

permissions:
  actions: write

jobs:
  setup:
    name: "checkout & Setup Terraform"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEV_ORG_PAT_TOKEN }}
      - uses: hashicorp/setup-terraform@v3


  terraform_plan:
    name: Terraform "init, validate, Plan"
    runs-on: self-hosted
    needs: setup
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEV_ORG_PAT_TOKEN }}
      - uses: hashicorp/setup-terraform@v3
    
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: infra_ApplicationGway/parent_module

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: infra_ApplicationGway/parent_module

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -out=tfplan
        working-directory: infra_ApplicationGway/parent_module


  terraform_apply:
        name: Terraform "Apply"
        runs-on: self-hosted
        needs: terraform_plan
        steps:
          - uses: actions/checkout@v4
            with:
              token: ${{ secrets.DEV_ORG_PAT_TOKEN }}
          - uses: hashicorp/setup-terraform@v3  
     
          - name: Terraform Init
            id: init
            run: terraform init -input=false
            working-directory: infra_ApplicationGway/parent_module

          - name: Terraform apply
            id: apply
            run: terraform apply --auto-approve -no-color
            working-directory: infra_ApplicationGway/parent_module
